server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/info-currency;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    name:
    username: info-currency
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: pl.lodz.p.zzpj.domain.util.FixedH2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    hibernate:
      ddl-auto: create
  mail:
    host: localhost
    port: 25
    username:
    password:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
icurrency:
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
